version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thedarknight
    environment:
      - APPLICATION_PORT=3310
      - DATABASE_URL=mongodb://host.docker.internal/EventTrack
      - DATABASE_SSL=false
      - FOREST_AUTH_SECRET=5a73e4b08b37edd31ee0468ca748ee8120c1f3b35abda270fa37e69ee5bb651ddcf32d36cc9336367b99cffc153f20e3
      - FOREST_ENV_SECRET=8f3a99a7148e5ca8ff96600448888636ece06802f1a14ff9aec4c2d65a1cc9c1
    ports:
      - "3310:3310"
    volumes:
      - ./:/usr/src/app
