// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
const mongoose = require('mongoose');

// This section contains the properties of your model, mapped to your collection's properties.
// Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
const schema = mongoose.Schema({
  'author': {
    id: mongoose.Schema.Types.ObjectId,
    username: String,
  },
  'category': String,
  'createdAt': Date,
  'description': String,
  'image': String,
  'image2': String,
  'imageId': String,
  'name': String,
  'subImage': String,
}, {
  timestamps: false,
});

module.exports = mongoose.model('events', schema, 'events');
