// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
const mongoose = require('mongoose');

// This section contains the properties of your model, mapped to your collection's properties.
// Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
const schema = mongoose.Schema({
  'email': String,
  'firstName': String,
  'hash': String,
  'image': String,
  'imageId': String,
  'isVerified': Boolean,
  'lastName': String,
  'salt': String,
  'sex': String,
  'username': String,
  'verificationToken': String,
  'verificationTokenExpires': Date,
}, {
  timestamps: false,
});

module.exports = mongoose.model('users', schema, 'users');
